pdl:
  url: ${PDL_URL:-http://0.0.0.0:8099/graphql}
  scope: ${PDL_SCOPE:-test}

azure:
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:-http://localhost:8098/token}
  clientId: ${AZURE_APP_CLIENT_ID:-test}
  clientSecret: ${AZURE_APP_CLIENT_SECRET:-test}
