pdl:
  url: https://pdl-api.dev-fss-pub.nais.io/graphql
  scope: api://dev-fss.pdl.pdl-api/.default

kafka:
  pool: nav-dev
  permanent-delete-topics: true

norg:
  url: https://norg2.dev-fss-pub.nais.io/norg2
  acl: norg2.dev-fss-pub.nais.io
