toggle:
  settOppAktørStream: "false"
pdl:
  url: https://pdl-api.prod-fss-pub.nais.io/graphql
  scope: api://prod-fss.pdl.pdl-api/.default

kafka:
  pool: nav-prod
  permanent-delete-topics: false
  acl:
    dev: []

norg:
  url: https://norg2.prod-fss-pub.nais.io/norg2
  acl: norg2.prod-fss-pub.nais.io
