apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: personopplysninger
  namespace: aap
  labels:
    team: aap
  annotations:
    githubUrl: "https://github.com/navikt/aap-personopplysninger"
spec:
  image: {{image}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /actuator/healthy
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/healthy
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  env:
    - name: PDL_URL
      value: {{pdl.url}}
    - name: PDL_SCOPE
      value: {{pdl.scope}}
