toggle:
  settOppAktørStream: ${TOGGLE_SETT_OPP_AKTØRSTREAM}
pdl:
  url: ${PDL_URL}
  scope: ${PDL_SCOPE}

norg:
  url: ${NORG_URL}

azure:
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
  clientId: ${AZURE_APP_CLIENT_ID}
  clientSecret: ${AZURE_APP_CLIENT_SECRET}

kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  ssl:
    truststorePath: ${KAFKA_TRUSTSTORE_PATH}
    keystorePath: ${KAFKA_KEYSTORE_PATH}
    credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}

schema-registry:
  url: ${KAFKA_SCHEMA_REGISTRY}
  user: ${KAFKA_SCHEMA_REGISTRY_USER}
  password: ${KAFKA_SCHEMA_REGISTRY_PASSWORD}
