pdl:
  url: ${PDL_URL}
  scope: ${PDL_SCOPE}

proxy:
  base-url: ${PROXY_BASEURL}

azure:
  tokenEndpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
  clientId: ${AZURE_APP_CLIENT_ID}
  clientSecret: ${AZURE_APP_CLIENT_SECRET}

kafka:
  application-id: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  truststorePath: ${KAFKA_TRUSTSTORE_PATH}
  keystorePath: ${KAFKA_KEYSTORE_PATH}
  credstorePsw: ${KAFKA_CREDSTORE_PASSWORD}
  clientId: ${KAFKA_CLIENT_ID:-personopplysninger}
