apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nom-skjerming
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  accessPolicy:
    outbound:
      rules:
        - application: skjermede-personer-pip
          namespace: nom
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /actuator/healthy
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/healthy
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
