name: nom-skjerming

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/nom-skjerming/**'
      - '.github/workflows/nom-skjerming.yml'

env:
  IMAGE: ghcr.io/navikt/${{ github.repository }}/${{ github.workflow }}:${{ github.sha }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test apps:${{ github.workflow }}:shadowJar --continue --no-daemon

      - uses: dorny/test-reporter@v1.5.0
        if: always()
        with:
          name: 🧬 Test results
          path: "apps/**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg, tag og push Docker image
        run: |
          docker build --build-arg APP=${{ github.workflow }} --pull --tag ${{ env.IMAGE }} --tag ghcr.io/${{ github.repository }}/${{ github.workflow }}:latest .
          docker push ghcr.io/navikt/${{ github.repository }}/${{ github.workflow }} --all-tags

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/${{ github.workflow }}/nais.yml
#          VARS: apps/${{ github.workflow }}/dev.yml
